hoops:
- orientation:
    p: 45
    r: 0
    y: 0
  position:
    x: 5.0
    y: 0.0
    z: 3.0
  radius: 1.0

- orientation:
    p: 0
    r: 0
    y: 0
  position:
    x: 47.0
    y: -2.0
    z: 3.0
  radius: 0.8

- orientation:
    p: 0
    r: 0
    y: 0
  position:
    x: 69.0
    y: 3.0
    z: 5.0
  radius: 1.4

- orientation:
    p: 30
    r: 0
    y: 15
  position:
    x: 94.0
    y: 1.0
    z: 4.0
  radius: 1.1

- orientation:
    p: -15
    r: 0
    y: 0
  position:
    x: 107.0
    y: -1.0
    z: 3.0
  radius: 0.6

- orientation:
    p: 0
    r: 0
    y: 0
  position:
    x: 141.0
    y: 0.0
    z: 3.0
  radius: 1.0

- orientation:
    p: -15
    r: 0
    y: 30
  position:
    x: 196.0
    y: 0.0
    z: 6.0
  radius: 0.7